import Layout from '@/components/layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from "../../public/images/profile/developer-pic-1.png"
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/icons'
import HireMe from '@/components/HireMe'
import lightBulb from "../../public/images/svgs/miscellaneous_icons_1.svg"
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <TransitionEffect/>
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light '>
        <Layout className='pt-0 md:p-16 sm:pt-8'>
          <div className = "flex items-center justify-between w-full lg:flex-col">
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="sujal" className='w-2/3 h-2/3 lg:hidden md:inline-block md:w-full sm:py-16 md:py-12 lg:py-8' priority sizes='(max-width:768px) 100vh, (max-width:1200px) 50vh,50vh'  />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center'>
              <AnimatedText text="Solving Complex Problems With Logic, Code, And Innovation. " className='!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl'/>
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs'>
              As a passionate problem-solver, I turn ideas into efficient and innovative solutions. Explore my latest projects and articles, showcasing my expertise in algorithms, AI, and full-stack development.
              </p>
              <div className='flex items-center self-start mt-2 lg:self-center'>


                <Link href="/sujalresume.pdf" target={'_blank'} 
                className='flex items-center bg-dark text-light p-2.5 
                px-6 rounded-lg font-semibold hover:bg-light hover:text-dark 
                border-2 border-solid border-transparent hover:border-dark dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                md:p-2 md:px-4 md:text-base'
                download={true}>Resume<LinkArrow className={"w-6 ml-1 "}/></Link>


                <Link href="mailto:kalrasujal322@gmail.com" target={'_blank'}
                className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'>Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe/>
        <div className='absolute right-8 bottom-8 inline-block w-20 md:hidden'>
          <Image src={lightBulb} alt="SujalBulb" className='w-full h-auto'/>
        </div>
      </main>
    </>
  )
}
